//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
        public int Salary { get; set; }
        public string CompanyName { get; set; }
        public string Postion { get; set; }
        public string RequiredAge { get; set; }
        public string Gender { get; set; }
        public string Requirements { get; set; }
        public string Type { get; set; }
        public int PostNo { get; set; }
        public string status { get; set; }
        public System.DateTime TimeofPost { get; set; }
        public Nullable<int> EmployerId { get; set; }
    }
}
